services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env.docker
    ports:
      # on expose le port uniquement en dev
      - 5433:5432
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
  redis:
    image: redis
    container_name: redis
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s